version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  configuration: docs/sphinx/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

# Build documentation in docs/sphinx/ directory
# Output directory: docs/sphinx/_build/html
