# Unipress Global Game Settings
# These are default values for all games in the collection

[game]
# Difficulty level (1-10): 1=easy, 10=hard
difficulty = 5

# Number of lives per game
lives = 3

# Start games in fullscreen mode
fullscreen = true

[ui]
# Duration of player blinking effect after losing a life (seconds)
blink_duration = 1.0

# Default language for UI messages (pl_PL = Polish, en_US = English)
language = "pl_PL"

[logging]
# Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
level = "INFO"

# Enable console output (for development)
console_enabled = true

# Enable file logging
file_enabled = true

# Log file path (supports loguru time formatting)
file_path = "logs/unipress-{time:YYYY-MM-DD}.log"

# Log file rotation (when to create new file)
rotation = "10 MB"

# Log retention (how long to keep old logs)
retention = "30 days"

# Compression for rotated logs
compression = "gz"

# Log format: "json" for structured logging, "human" for development
format = "json"