# Demo Jump Game Settings
# These override global settings for the demo jumping game

[game]
# Demo game uses easier difficulty and more lives
difficulty = 3
lives = 1

# [ui]
# Override language for this specific game
# language = "en_US"

[demo_jump]
# Game-specific settings for demo jump game
obstacle_speed_base = 100
jump_height_base = 150