name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]
    paths: [ 'docs/**', 'unipress/**', 'pyproject.toml' ]
  pull_request:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"
      
      - name: Install dependencies
        run: |
          uv sync --group dev
      
      - name: Build documentation
        run: |
          cd docs/sphinx
          uv run sphinx-build -b html . _build/html
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/sphinx/_build/html
